version: "3.8"
services:
  scrapyd:
    build: .
    ports:
      - "6800:6800"
    volumes:
      - ./data:/var/lib/scrapyd
      - .:/code
    working_dir: /code
    depends_on:
      - "db"
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/db/data:/var/lib/mysql
      - ./data/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
